#!/usr/bin/env bash

# Update packages and install Nginx
apt-get update
apt-get install nginx -y

# Configure Nginx to listen on port 80 of all active IPv4 IPs
sed -i 's/listen \[::\]:80 default_server;/listen 80 default_server;/g' /etc/nginx/sites-available/default
service nginx restart

