#!/usr/bin/env bash
# configures an ubuntu server

if [ "$(whoami)" != "root" ]; then
	echo "This script must be run as root or with sudo!"
	exit 1
fi

cp /etc/hosts /tmp/hosts.new
sed -i 's/^127.0.0.1.*$/127.0.0.2 localhost/g' /tmp/hosts.new
echo '8.8.8.8 facebook.com' >> /tmp/hosts.new
cp -f /tmp/hosts.new /etc/hosts

echo "Hosts file updated!"
exit 0
