#!/usr/bin/env bash
# configures an ubuntu server

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root" 2>&1
	exit 1
fi

echo "This script will modify your /etc/hosts file to configure your server."
read -p "Do you want to proceed? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
	cp /etc/hosts ~/hosts.new
	if ! sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new; then
		echo "Failed to modify the hosts file" 2>&1
		exit
	fi
	if ! echo -e "8.8.8.8\tfacebook.com" >> ~/hosts.new; then
		echo "Failed to modify the hosts file" 2>&1
		exit
	fi
	if ! cp -f ~/hosts.new /etc/hosts; then
		echo "Failed to copy the modified hosts file" 2>&1
		exit 1
	fi
	echo "The /etc/hosts file has been successfully modified."
else
	echo "The script has been cancelled."
fi
