#!/usr/bin/env bash
# Configure nginx to run as non-root and listen on port 8090
# Stop the Nginx service if it's already running
service nginx stop

# Modify the Nginx configuration to run as the nginx user
sed -i 's/user .*/user nginx;/g' /etc/nginx/nginx.conf

# Start the Nginx service
service nginx start

